server:
  port: 8080
  servlet:
    context-path: /private-hospital

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always


spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: NON_NULL
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: healthcare
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas:
      - healthcare
    default-schema: healthcare
    baseline-on-migrate: true

jwt:
  secret: b5baf536-6ed2-4185-817a-3fdd406c8553