CREATE
EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE HOSPITAL_USER
(
    ID       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    USERNAME VARCHAR(255) UNIQUE,
    NAME     VARCHAR(255),
    PASSWORD VARCHAR(255)
);

CREATE TABLE DOCTOR
(
    ID        UUID PRIMARY KEY DEFAULT uuid_generate_v4() REFERENCES HOSPITAL_USER (ID),
    SPECIALTY VARCHAR(255)
);

CREATE TABLE PATIENT
(
    ID       UUID PRIMARY KEY DEFAULT uuid_generate_v4() REFERENCES HOSPITAL_USER (ID),
    SYMPTOMS VARCHAR(255)
);

CREATE TABLE APPOINTMENT
(
    ID         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    DOCTOR_ID  UUID REFERENCES DOCTOR (ID),
    PATIENT_ID UUID REFERENCES PATIENT (ID),
    START_DATE TIMESTAMP,
    END_DATE   TIMESTAMP,
    REASON     VARCHAR(255)
);

ALTER TABLE APPOINTMENT
    ADD CONSTRAINT UNIQUE_APPOINTMENT_HOUR UNIQUE (DOCTOR_ID, START_DATE, END_DATE);

CREATE TABLE ROLE
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(20)
);

CREATE TABLE USER_ROLE
(
    ID      SERIAL PRIMARY KEY,
    USER_ID UUID REFERENCES HOSPITAL_USER (ID),
    ROLE_ID INTEGER REFERENCES ROLE (ID)
);

INSERT INTO ROLE (ID, NAME)
VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLE (ID, NAME)
VALUES (2, 'ROLE_PATIENT');
INSERT INTO ROLE (ID, NAME)
VALUES (3, 'ROLE_DOCTOR');